global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ticket price service'
    static_configs:
      - targets: ['158.160.24.206:8000']