name: Deploy to cloud
on: workflow_dispatch

env:
  WORKDIR: ~/infra

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Move files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.INFRA_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "mlflow,docker-compose.yaml"
          target: WORKDIR
      - name: Restart containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.INFRA_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: whoami
